blueprint:
  name: Light with Auto Off Delay
  description: Turn a light off automatically after a specified delay
  domain: automation
  source_url: https://github.com/DaGolle/HomeAssistantBlueprints/light_with_auto_off_delay.yaml
  input:
    light_entity:
      name: Light
      selector:
        entity:
          domain: light
    off_delay:
      name: Delay time
      description: Delay time after which to turn off the light.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If light is switched off within delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input light_entity
    from: "off"
    to: "on"
    id: "light_on"
  - platform: state
    entity_id: !input light_entity
    from: "on"
    to: "off"
    id: "light_off"

action:
  - choose:
    # start delay when light is turned on
    - conditions:
        - condition: trigger
          id: "light_on"
      sequence:
        - delay: !input off_delay
        - service: light.turn_off
          target:
            entity_id: !input light_entity
    # do nothing when light is turned off
    # in order to stop the delay
    - conditions:
        - condition: trigger
          id: "light_off"
      sequence: []
